DEL /F /S /Q "*.db"
DEL /F /S /Q "*.ipch"
DEL /F /S /Q "*.dat"
RMDIR /S /Q "Debug"
RMDIR /S /Q "Release"
RMDIR /S /Q "x64"
RMDIR /S /Q "Project1\Debug"
RMDIR /S /Q "Project1\Release"
RMDIR /S /Q "Project1\x64"
RMDIR /S /Q ".vs\Project1\v15\ipch"