DEL /F /S /Q /AH "*.suo"
DEL /F /S /Q "*.sdf"
DEL /F /S /Q "*.opensdf"
DEL /F /S /Q "*.db"
DEL /F /S /Q "*.iobj"
DEL /F /S /Q "*.ipdb"
DEL /F /S /Q "*.pdb"
DEL /F /S /Q "*.ilk"
DEL /F /S /Q "*.exe"
RMDIR /S /Q "LittleModelLoader/Debug"
RMDIR /S /Q "LittleModelLoader/Release""
RMDIR /S /Q "Debug""
RMDIR /S /Q "Release"
RMDIR /S /Q "ipch"
RMDIR /S /Q ".vs"